blank_issues_enabled: false
contact_links:
  - name: ğŸ“– DocumentaciÃ³n
    url: https://ar-js-org.github.io/AR.js-Docs/
    about: Consulta la documentaciÃ³n oficial de AR.js
  - name: ğŸ’¬ Discusiones
    url: https://github.com/daremappdaniel-dev/Ar_frame_mas_Ar.js/discussions
    about: Preguntas generales y discusiones
